### ISSUE TITLE
Getting  invalid arguments: hostname must be a string or falsey when running 'npm run dev'

### ISSUE THREAD

**Issue by whitejeffreyl** [AlohaCode/StartingWithReact#1]
TypeError: invalid arguments: hostname must be a string or falsey
    at Object.lookup (dns.js:113:11)
    at listenAfterLookup (net.js:1377:20)
    at Server.listen (net.js:1373:5)
    at Server.listen (/Users/jeff.white/Documents/workspace/StartingWithReact/demo-1/node_modules/webpack-dev-server/lib/Server.js:324:27)
    at processOptions (/Users/jeff.white/Documents/workspace/StartingWithReact/demo-1/node_modules/webpack-dev-server/bin/webpack-dev-server.js:209:38)
    at Object.<anonymous> (/Users/jeff.white/Documents/workspace/StartingWithReact/demo-1/node_modules/webpack-dev-server/bin/webpack-dev-server.js:228:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

**Comment by whitejeffreyl** [comment]
Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/Users/jeff.white/.npmbrew/current/bin/npm" "run" "dev"
npm ERR! node v5.4.0
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE
npm ERR! starting-with-react-01@0.0.0 dev: `NODE_ENV=development webpack-dev-server --content-base src --host $IP --port $PORT --config webpack.config.js --progress --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starting-with-react-01@0.0.0 dev script 'NODE_ENV=development webpack-dev-server --content-base src --host $IP --port $PORT --config webpack.config.js --progress --hot'.
npm ERR! This is most likely a problem with the starting-with-react-01 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development webpack-dev-server --content-base src --host $IP --port $PORT --config webpack.config.js --progress --hot
npm ERR! You can get their info via:
npm ERR!     npm owner ls starting-with-react-01
npm ERR! There is likely additional logging output above.

**Comment by isramos** [comment]
same issue here. How to run this Cloud9 app locally?

**Comment by isramos** [comment]
fix: edit package.json and use  "--host 0.0.0.0 --port 8080".

**Comment by AlohaCode** [comment]
This project is set up to run on Cloud 9, as the package.json config shows.  Glad you found proper config to run locally!
